services:
  service-a:
    build: 
      context: ./service-a
      dockerfile: Dockerfile
    env_file:
      - ./service-a/.env
    ports:
      - "8081:8081"
    depends_on:
      - service-b
      - otel-collector

  service-b:
    build:
      context: ./service-b
      dockerfile: Dockerfile
    env_file:
      - ./service-b/.env
    ports:
      - "8080:8080"
    depends_on:
      - otel-collector

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-config.yaml
    command: ["--config=/etc/otelcol-config.yaml"]
    ports:
      - "4317:4317"
      - "4318:4318"
      - "55681:55681"
    depends_on:
      - zipkin
